package builder

// global comment
var (
	commentGenerator = "File generated by crudgen. DO NOT EDIT"
	commentIssue     = "If you want report an issue, please visit http://github.com/ymohl-cl/gopkg/gocrud"
)
